apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - port: 80
      nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: userservice
  namespace: default
  labels:
    app: userservice
spec:
  containers:
  - name: userservice
    image: compulsory_assignment_example/userservice
    imagePullPolicy: Never